# 配置tomcat端口号
server:
  port: 9001
# 配置注册中心中当前应用名称，名称不要有下划线_
spring:
  application:
    name: rumo-web
  resources:
    static-locations: ["classpath:/static/"]
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 解决驼峰自动转下划线导致MySQL查询找不到字段
  datasource:
    url: jdbc:mysql://192.168.195.135:3306/rumoblog?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456